apiVersion: v1
kind: Pod
metadata:
  name: envfildref
spec:
  containers:
  - name: install
    image: nginx
    command: ["sh","-c"]
    args: 
    - while true; do echo -en '\n'; printenv MY_NODE_NAME; sleep 10; done;
    env:
      - name: MY_NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName

  dnsPolicy: Default

---
apiVersion: v1
kind: Pod
metadata:
  name: init-demo
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
  # These containers are run during pod initialization
  initContainers:
  - name: install
    image: busybox:1.28
    command: ["/bin/sh"]
    args: 
    - -c
    - while true; do echo Hoje É `TZ=':America/Sao_Paulo' date +'%m-%d-%Y'` e hora é `TZ=':America/Sao_Paulo' date +'%I:%M:%S %p'`; /work-dir/index.html; sleep 5; done
    volumeMounts:
    - name: workdir
      mountPath: "/work-dir"
  dnsPolicy: Default
  volumes:
  - name: workdir
    emptyDir: {}
