apiVersion: v1
kind: Pod
metadata:
  name: cka-pod-example-screts
spec:
  containers:
  - name: cka-pod-example-screts
    image: redis
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: secret-db
          key: user
    - name: SECRET_APSSWORD
      valueFrom:
        secretKeyRef:
          name: secret-db
          key: pass