apiVersion: v1
kind: Service
metadata:
  name: service-am-i-ready
  namespace: default
  labels:
    id: cross-server-ready
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    id: cross-server-ready
