apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: safari
  name: safari
  namespace: project-tiger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: safari
  strategy: {}
  template:
    metadata:
      labels:
        app: safari
    spec:
      volumes:  # add
      - name: data # add
        persistentVolumeClaim: # add
          claimName: safari-pvc # add
      containers:
      - image: httpd:2.4.41-alpine
        name: container
        volumeMounts: # add
        - name: data # add
          mountPath: /tmp/safari-data # add
