apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: liveness-httpget
  name: liveness-httpget
spec:
  containers:
  - image: nginx
    name: liveness-httpget
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3
  dnsPolicy: ClusterFirst
  restartPolicy: Always