apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: liveness-command
  name: liveness-command
spec:
  containers:
  - image: nginx
    name: liveness-command
    args:
    - "/bin/sh"
    - "-c"
    - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command: 
        - cat 
        - /tmp/healthy
      initialDelaySeconds: 3
      periodSeconds: 5
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}